language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - 'pypy'

# Install system dependencies
before_install:
  - 'sudo apt-get install python-dev libevent-dev'

# Install python dependencies
install:
  - 'pip install -e ".[test]" --use-mirrors'

# Run tests
script: nosetests
