language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
  - 'pypy'

# Install system dependencies
before_install:
  - 'travis_retry sudo apt-get install python-dev libevent-dev'

# Install python dependencies
install:
  - 'travis_retry pip install -e ".[test]" --use-mirrors'

# Blacklist legacy branches as they don't have operating tests
branches:
  except:
    - legacy/armet
    - legacy/flapjack

# Run tests
script: nosetests
